<?php

	echo '<div class="container">';
	echo '    <div class="col-md-12">';
	echo '        <br>';
	echo '        <h2><b>Education</b></h2>';
	echo '        <hr>';
	echo '        <h4><b><u>Expected Graduation: December 2022</u></b></h4>';
	echo '        <h3>University of Texas at San Antonio</h3>';
	echo '        <h4><b>Bachelor of Science in Computer Science</b> -- GPA: 3.91</h4>';
	echo '        <h3><u>Relevant Coursework</u></h3>';
	echo '        <ul>';
	echo '            <li>Software Engineering and Web Technologies</li>';
	echo '            <li>Analysis of Algorithms and Data Structures</li>';
	echo '            <li>Application and Systems Programming</li>';
	echo '            <li>Calculus and Discrete Mathematics</li>';
	echo '        </ul>';
	echo '        <br>';
	echo '        <h4><b><u>August 2016 - May 2020</u></b></h4>';
	echo '        <h3>San Antonio College</h3>';
	echo '        <h4><b>Associate of Science in Computer Science</b> -- GPA: 3.52</h4>';
	echo '        <h3><u>Graduated May 2020</u></h3>';
	echo '        <h3>Attended classes part-time while working full-time</h3>';
	echo '        <br>';
	echo '    </div>';
	echo '</div>';
	echo '<div class="container">';
	echo '    <div class="col-md-12">';
	echo '        <br>';
	echo '        <h3>Fall 2021 Schedule</h3>';
	echo '        <hr>';
	echo '        <table border="1">';
	echo '            <thead>';
	echo '                <tr>';
	echo '                    <th colspan="2" align="center">Class</th>';
	echo '                    <th align="center">Instructor</th>';
	echo '                    <th colspan="2" align="center">Time</th>';
	echo '                    <th align="center">Location</th>';
	echo '                    <th align="center">Final Grade</th>';
	echo '                </tr>    ';
	echo '            </thead>';
	echo '            <tbody>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3342</td>';
	echo '                    <td align="center">Analysis of Algorithms</td>';
	echo '                    <td align="center">Matt Gibson-Lobpez</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">8:30 AM - 9:45 AM</td>';
	echo '                    <td align="center">Online</td>';
	echo '                    <td align="center"><b>A</b></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3424</td>';
	echo '                    <td align="center">Systems Programming</td>';
	echo '                    <td align="center">Sam Silvestro</td>';
	echo '                    <td align="center">M - W - F</td>';
	echo '                    <td align="center">10:00 AM - 10:50 AM</td>';
	echo '                    <td align="center">Online</td>';
	echo '                    <td align="center"><b>A+</b></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3723</td>';
	echo '                    <td align="center">Programming Languages</td>';
	echo '                    <td align="center">Steven O\'Hara</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">11:15 AM - 12:30 PM</td>';
	echo '                    <td align="center">NPB 1.202</td>';
	echo '                    <td align="center"><b>B</b></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3773</td>';
	echo '                    <td align="center">Software Engineering</td>';
	echo '                    <td align="center">Juan Valadez</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">4:00 PM - 5:15 PM</td>';
	echo '                    <td align="center">MH 2.01.20</td>';
	echo '                    <td align="center"><b>A</b></td>';
	echo '                </tr>';
	echo '            </tbody>';
	echo '        </table>';
	echo '        <br>';
	echo '        <br>';
	echo '        <h3>Spring 2022 Schedule</h3>';
	echo '        <hr>';
	echo '        <table border="1">';
	echo '            <thead>';
	echo '                <tr>';
	echo '                    <th colspan="2" align="center">Class</th>';
	echo '                    <th align="center">Instructor</th>';
	echo '                    <th colspan="2" align="center">Time</th>';
	echo '                    <th align="center">Location</th>';
	echo '                </tr>    ';
	echo '            </thead>';
	echo '            <tbody>';
	echo '                <tr>';
	echo '                    <td align="center">CS-4413</td>';
	echo '                    <td align="center">Web Technologies</td>';
	echo '                    <td align="center">Juan Valadez</td>';
	echo '                    <td align="center">M - W - F</td>';
	echo '                    <td align="center">10:00 AM - 10:50 AM</td>';
	echo '                    <td align="center">NPB 1.202</td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3733</td>';
	echo '                    <td align="center">Operating Systems</td>';
	echo '                    <td align="center">Sam Silvestro</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">8:30 AM - 9:45 AM</td>';
	echo '                    <td align="center">MH 3.04.22</td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3743</td>';
	echo '                    <td align="center">Database Systems</td>';
	echo '                    <td align="center">Mauricio Gomez</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">1:00 PM - 2:15 PM</td>';
	echo '                    <td align="center">SEB 3.146</td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3793</td>';
	echo '                    <td align="center">Artificial Intelligence</td>';
	echo '                    <td align="center">Kevin Desai</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">2:30 PM - 3:45 PM</td>';
	echo '                    <td align="center">BB 2.01.18</td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">CS-3853</td>';
	echo '                    <td align="center">Computer Architecture</td>';
	echo '                    <td align="center">Wei Wang</td>';
	echo '                    <td align="center">T - R</td>';
	echo '                    <td align="center">4:00 PM - 5:15 PM</td>';
	echo '                    <td align="center">MH 3.04.10</td>';
	echo '                </tr>';
	echo '            </tbody>';
	echo '        </table>';
	echo '        <br>';
	echo '    </div>';
	echo '</div>';

?>