<?php

	echo '<div class="container">';
	echo '    <div class="col-md-12">';
	echo '        <br>';
	echo '        <h2><b>Experience</b></h2>';
	echo '        <hr>';
	echo '        <h4><b><u>August 2021 - Present</u></b></h4>';
	echo '        <h3><b>Undergraduate TA/Grader - UTSA Department of Computer Science</b></h3>';
	echo '        <ul>';
	echo '            <li>Courses: Discrete Mathematics and Computer Organization</li>';
	echo '            <li>Review students\' logic, mathematics and code critical to computer science</li>';
	echo '        </ul>';
	echo '        <br>';
	echo '        <h4><b><u>September 2011 - August 2021</u></b></h4>';
	echo '        <h3><b>Retail Management Career</b></h3>';
	echo '        <h4><b>Worked up to management positions at multiple companies within Pet-Specialty retail in order to pay for college and living expenses</b></h4>';
	echo '        <ul>';
	echo '            <li>Highest Position: General Manager of medium-sized corporate retail store (Petco)</li>';
	echo '            <li>Responsibilities: Serve as operator of all business functions of the store. Oversee and forecast sales, monitor inventory and ';
	echo '                budgets, review and respond to metrics and internal data, facilitate a positive customer service experience. Manage staff by ';
	echo '                hiring, maintaining and developing team members, including other store leadership and resolving any organizational or ';
	echo '                interpersonal conflicts.';
	echo '            </li>';
	echo '            <li>Achievements: Selected for public speaking roles at training conferences and as an actor for training videos</li>';
	echo '        </ul>';
	echo '        <br>';
	echo '        <h2><b>Technical Skills</b></h2>';
	echo '        <hr>';
	echo '        <ul>';
	echo '            <li>Languages: Expert in Python, C, Java and C#. Proficient in JavaScript, PHP, CSS, and Assembly</li>';
	echo '            <li>Frameworks/Services: Proficient with django, Vue, NPM, Unity, AWS</li>';
	echo '            <li>Operating Systems: Unix/Linux, Windows, MacOS, iOS, Android</li>';
	echo '            <li>Ability to rapidly learn new languages and frameworks, comfortable in any development environment</li>';
	echo '        </ul>';
	echo '        <br>';
	echo '        <h2><b>Additional Skills</b></h2>';
	echo '        <hr>';
	echo '        <ul>';
	echo '            <li>Strong Business Acumen - management principles, business strategy and market knowledge</li>';
	echo '            <li>Seasoned Leader - Over eight years of management experience, passionate work ethic, positive attitude and an ';
	echo '                approachable/developmental leadership style';
	echo '            </li>';
	echo '            <li>Great Communicator - strong interpersonal skills developed from over ten years of customer service and business communication</li>';
	echo '            <li>Fluent Writer - professional writing and code documentation</li>';
	echo '        </ul>';
	echo '        <br>';
	echo '    </div>';
	echo '</div>';
	echo '<div class="container">';
	echo '    <div class="col-md-12">';
	echo '        <br>';
	echo '        <h3>Progress of Notable Projects</h3>';
	echo '        <hr>';
	echo '        <table border="1">';
	echo '            <thead>';
	echo '                <tr>';
	echo '                    <th align="center">Date Completed</th>';
	echo '                    <th align="center">Description</th>';
	echo '                    <th align="center">Languages and Frameworks</th>';
	echo '                    <th colspan="2" align="center">Links</th>';
	echo '                </tr>';
	echo '            </thead>';
	echo '            <tbody>';
	echo '                <tr>';
	echo '                    <td align="center">February 2020</td>';
	echo '                    <td align="center">Wedding Website</td>';
	echo '                    <td align="center">Python, HTML/CSS, Django, Heroku</td>';
	echo '                    <td colspan="2"><a href="http://ryanandlaura2020.com" target="_blank">ryanandlaura2020.com</a></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">September 2020</td>';
	echo '                    <td align="center">Recursive Large Text Reversal</td>';
	echo '                    <td align="center">C</td>';
	echo '                    <td colspan="2"><a href="https://github.com/ryanGill8120/large-text-reversal" target="_blank">github.com</a></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">April 2021</td>';
	echo '                    <td align="center">Calorie/Workout Tracker Desktop App</td>';
	echo '                    <td align="center">Java, JavaFX</td>';
	echo '                    <td colspan="2"><a href="https://github.com/ryanGill8120/energy-balance" target="_blank">github.com</a></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">November 2021</td>';
	echo '                    <td align="center">Hotel Booking Web App (Frontend)</td>';
	echo '                    <td align="center">Javascript, HTML/CSS, PHP, Vue3</td>';
	echo '                    <td colspan="2"><a href="http://www.turinghotels.com/" target="_blank">www.turinghotels.com</a></td>';
	echo '                </tr>';
	echo '                <tr>';
	echo '                    <td align="center">February 2022</td>';
	echo '                    <td align="center">Puzzle Creator API</td>';
	echo '                    <td align="center">Python, Django Rest Framework, Heroku</td>';
	echo '                    <td ><a href="https://github.com/ryanGill8120/PuzzleCreator_base" target="_blank">github.com</a></td>';
	echo '                    <td ><a href="https://puzzle-creator-api.herokuapp.com/sudoku/5/" target="_blank">Sudoku GET sample</a></td>';
	echo '                </tr>';
	echo '            </tbody>';
	echo '        </table>';
	echo '        <br>';
	echo '    </div>';
	echo '</div>';

?>